title: "JS SBU"
email: js.team@brainstation-23.com
formskey: xbjeqboj
timezone: "Asia/Dhaka"
baseurl: "/js-sbu"
permalink: "/:title/"
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
author: "JS SBU"
paginate: 30
disqus: "jssbusite"
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: compressed
ganalytics: UA-113961478-1

# Authors
authors:
  JS_SBU:
    name: JS_SBU
    display_name: SJ SBU
    avatar: "assets/images/logo.png"
    email: js.team@brainstation-23.com
    web: https://brainstation-23.com/
    description: "JS-SBU unit at Brain Station 23 Ltd is dedicated to using the latest JavaScript technologies to create high-quality, efficient, and scalable applications for their clients. With their expertise in Node.js, React, Angular, ReactNative, Shopify, and Flutter, they are able to deliver customized solutions that meet their clients' specific needs and help them achieve their business goals."

# Social
social:
  linkedIn: https://www.linkedin.com/company/brain-station-23/
  facebook: https://www.facebook.com/brainstation23/
  twitter: https://twitter.com/BrainStation23

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
